/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-north-1",
    "aws_appsync_graphqlEndpoint": "https://366blmig2jhahhtmhzzmamawue.appsync-api.eu-north-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-north-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-mxzmksgjijcb5fpn7nmhvgolue",
    "aws_cognito_identity_pool_id": "eu-north-1:d5681eee-85ac-4d8a-9351-97fd1f7b63c7",
    "aws_cognito_region": "eu-north-1",
    "aws_user_pools_id": "eu-north-1_RxjZ6Ww8O",
    "aws_user_pools_web_client_id": "2oc1l9ko4mi5l4a6o5uoifjl1q",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
